# This is a basic workflow to help you get started with Actions

name: AKS Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in paralle
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
       versionSpec: '5.x'
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 3.1.x
        # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
    - name: dotnet build
      run: dotnet build -c release
    - name: docker build
      run: docker build -t githubactions-aks-demo:'${{github.sha}}' .
    
    - uses: azure/docker-login@v1
      with:
        login-server: garegistry1.azurecr.io .
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . garegistry1.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        docker push garegistry1.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
      
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
        creds: '${{secrets.AZURE_CREDENTIALS}}'
        # Resource Group Name
        resource-group: appservices
        # AKS Cluster Name
        cluster-name: ga-aks-demo-cluster

  # Create K8s secrets to pull images
    - name: Create secret in Kubernetes cluster
      uses: Azure/k8s-create-secret@v1.1
      with:
        # Container registry url
        container-registry-url: garegistry1.azurecr.io 
        # Container registry username
        container-registry-username: '${{secrets.REGISTRY_USERNAME}}'
        # Container registry password
        container-registry-password:  '${{secrets.REGISTRY_PASSWORD}}'
        # Type of Kubernetes secret. For example, docker-registry or generic
        secret-type: docker-registry
        # Name of the secret. You can use this secret name in the Kubernetes YAML configuration file.
        secret-name: docker-image-pull-secret
        
      # Deploy to k8s cluster
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1
      with:        
        # Path to the manifest files which will be used for deployment.
        manifests: |
          k8s/deployment.yml
          k8s/service.yml
        # Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test
        images: '${{secrets.REGISTRY_USERNAME}}/githubactions-aks-demo:${{github.sha}}'
        # Name of a docker-registry secret that has already been set up within the cluster. Each of these secret names are added under imagePullSecrets field for the workloads found in the input manifest files
        imagepullsecrets: docker-image-pull-secret
        # deploy/promote/reject
        action: deploy
        
    
        
    
